### ISSUE TITLE
[style] how to style DropdownMenu.Item style on android?

### ISSUE THREAD

**Issue by 321paranoiawhy** [nandorojo/zeego#100]
I try this code on android to style:

```tsx
<DropdownMenu.Item
key={'退出系统'}
textValue={'退出系统'}
style={{height: 200, backgroundColor: 'red'}}
onSelect={() => console.log('退出系统')}
>
  <DropdownMenu.ItemTitle>退出系统</DropdownMenu.ItemTitle>
</DropdownMenu.Item>
```

but nothing happens, code below behaves the same:

```tsx
<DropdownMenu.ItemTitle>
  <Text className="text-red-500" style={{fontSize: 80}}>
    系统设置
  </Text>
</DropdownMenu.ItemTitle>
```

**Comment by wolfcarves** [comment]
tried all work arounds but still haven't found a solution, probably this library have a bug.

**Comment by nandorojo** [comment]
You can only style web. Native menus don’t accept text styles. But you can pass the `destructive` prop to item

**Comment by 321paranoiawhy** [comment]
> You can only style web. Native menus don’t accept text styles. But you can pass the `destructive` prop to item

I will try it.
