### ISSUE TITLE
Sharp edges on box shadow

### ISSUE THREAD

**Issue by jinky77** [nandorojo/zeego#101]
Here is my code:

```
<DropdownMenu.Root>
  <DropdownMenu.Trigger>
    <Ionicons name="ellipsis-horizontal" size={24} />
  </DropdownMenu.Trigger>
  <DropdownMenu.Content>
    <DropdownMenu.Label>My Label</DropdownMenu.Label>
    <DropdownMenu.Item key="xyz">
      <DropdownMenu.ItemTitle>My Item</DropdownMenu.ItemTitle>
    </DropdownMenu.Item>
  </DropdownMenu.Content>
</DropdownMenu.Root>
```
And the result:

<img width="287" alt="Capture d’écran 2024-09-05 à 22 13 00" src="https://github.com/user-attachments/assets/8e744696-872b-4e83-b945-5e0d311e957e">

I'm getting sharp edges on box shadow and I can't figure out why. I tried on an Android physical device as well and get the same result.

Can `@react-native-menu/menu` be responsible for this? I get the same sharp edges result outside of Zeego when importing `MenuView` component. Thanks!

**Comment by nandorojo** [comment]
This is Android right? yeah this would all be upstream on the react-native-menu package, and this might even be a native android issue...going to close as zeego can't fix this (unless we make our own custom android menu someday, maybe for v3)
