### ISSUE TITLE
Failed to Pod Install

### ISSUE THREAD

**Issue by YaoHuiJi** [nandorojo/zeego#103]
When install zeego 1.1.0.0, there is an error occurred when running 'pod install':

> [!] Unable to find a specification for `ExpoModulesCore` depended upon by `ReactNativeIosUtilities`
>
>You have either:
> * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo->update`.
> * mistyped the name or version.
> * not added the source repo that hosts the Podspec to your Podfile.

Could you please tell me which version of `react-native-ios-utilities` can work well with zeego? version 1?

**Comment by nandorojo** [comment]
I think the latest should should work if you copy the install scripts from the readme

**Comment by YaoHuiJi** [comment]
> I think the latest should should work if you copy the install scripts from the readme

Thank you for the reply, but I have already read the whole documentation and followed the instructions for installation. Can you tell me which 'install scripts' I might have missed? Also, my project is not using Expo, is it required?

**Comment by iansamz** [comment]
I'm experiencing he same issue. I'm working on a non-Expo project

**Comment by nandorojo** [comment]
There is a section for “iOS”

https://zeego.dev/start#ios

**Comment by YaoHuiJi** [comment]
> There is a section for “iOS”
> 
> https://zeego.dev/start#ios

Only one line `yarn add react-native-ios-context-menu react-native-ios-utilities` in 'iOS' section, and `Run pod install in your ios folder` at the bottom of that page. 

I choose not to use this library days ago, so if you think there's no issue, feel free to close it.

**Comment by nandorojo** [comment]
Yeah that install script worked for me. But sounds good
