### ISSUE TITLE
Always anchor menu to the bottom

### ISSUE THREAD

**Issue by acdifran** [nandorojo/zeego#107]
When an item is near the top of the screen it nicely moves the trigger content to the center when displaying the context menu to make sure everything is fully displayed. However, when an item is near the bottom, instead of moving the item to the center to display the menu the menu just displays "above" the trigger content instead. This causes it to overlap the auxiliary menu if ones exists. Is there any way to ensure the menu is always anchored to the bottom?

https://github.com/user-attachments/assets/e2184422-a4db-4ef6-a291-1ad5b747a287

**Comment by acdifran** [comment]
FYI definitely an issue in the upstream library: https://github.com/dominicstop/react-native-ios-context-menu/issues/102#issuecomment-2457776333

**Comment by nandorojo** [comment]
The menu item placement is a native iOS thing

however the auxiliary view should position itself properly, you may need to add some custom props to it. Can you see the chat example on the upstream iOS library?

**Comment by acdifran** [comment]
hey @nandorojo yeah the aux menu will position itself properly if the menu flips if you don't specify a fixed anchor point, so that part works just fine. The issue is getting the main menu to always be on the bottom. We can just track on the upstream library issue, so will go ahead and close this out.
