### ISSUE TITLE
Error: Cannot find native module 'RNIContextMenuView', js engine: hermes [Component Stack]

### ISSUE THREAD

**Issue by xushnud123** [nandorojo/zeego#111]
"zeego": "^2.0.3"
import { View, Text, Image } from "react-native";
import * as DropdownMenu from "zeego/dropdown-menu";
import React from "react";
import { icons } from "@/constants";

const Menu = () => {
  return (
    <View>
      <DropdownMenu.Root>
        <DropdownMenu.Trigger>
          <Image source={icons.menu} className='w-5 h-5' resizeMode='contain' />
        </DropdownMenu.Trigger>
        <DropdownMenu.Content>
          <DropdownMenu.Item key='1'>
            <DropdownMenu.ItemTitle>title 1</DropdownMenu.ItemTitle>
          </DropdownMenu.Item>
        </DropdownMenu.Content>
      </DropdownMenu.Root>
    </View>
  );
};

export default Menu;

**Comment by nandorojo** [comment]
Please follow the installation steps

**Comment by xushnud123** [comment]
@nandorojo i did all the sequence but i still get the error 

Error: Cannot find native module 'RNIContextMenuView', js engine: hermes [Component Stack] zeego error

**Comment by AustineA** [comment]
Somehow i found myself here. 😅

**Comment by nandorojo** [comment]
Does disabling new architecture help?

**Comment by TechchazeInc** [comment]
I am facing this too. 

(NOBRIDGE) ERROR  Error: Cannot find native module 'RNIContextMenuView'

**Comment by nandorojo** [comment]
Like I said in my previous comment, I believe it’s a new arch issue. Does disabling it fix this?

**Comment by AustineA** [comment]
> Like I said in my previous comment, I believe it’s a new arch issue. Does disabling it fix this?

Nope!

**Comment by nandorojo** [comment]
Potential fix here: https://github.com/nandorojo/zeego/issues/130

**Comment by nandorojo** [comment]
Rebuild the dev client

**Comment by AustineA** [comment]
@MarzyCoder Yes. You can also clear the cache with `npx expo prebuld -p ios --clean`. After that run `npx expo run:ios`

**Comment by AustineA** [comment]
For me, I, stayed on SDK 51.
