### ISSUE TITLE
Opinionated UI render 

### ISSUE THREAD

**Issue by clayrisser** [nandorojo/zeego#13]
Fully great 👍 work, but do you think using radix is abstracting this at the wrong place? Are there plans to separate the API from the rendering?

I want to use this with react-native-web/dripsy instead of radix for the web platform.

**Comment by nandorojo** [comment]
the web side uses react native web for rendering. radix is just a layer on top for web. have you seen the dripsy example?

**Comment by clayrisser** [comment]
Not yet. I'll take a look and probably all my questions will be answered.

**Comment by nandorojo** [comment]
it’ll be clearer once i find time to make a docs site!
