### ISSUE TITLE
Expose onOpenChange

### ISSUE THREAD

**Issue by robertherber** [nandorojo/zeego#14]
I guess this might be hard to support cross-platform, but it would be great if it's possible. Radix has a onOpenChange callback that  makes it possible to know whether a DropdownMenu is open or not. I'm thinking it might be worth to add it even if it's not possible cross-platform (should of course be made clear through JSDoc etc in that case)?

My specific use-case:
I needed this to be able to disable key listeners on web, so escape can work as expected

```diff
diff --git a/node_modules/zeego/lib/module/dropdown-menu/dropdown-menu.web.js b/node_modules/zeego/lib/module/dropdown-menu/dropdown-menu.web.js
index 9745390..b0a57e7 100644
--- a/node_modules/zeego/lib/module/dropdown-menu/dropdown-menu.web.js
+++ b/node_modules/zeego/lib/module/dropdown-menu/dropdown-menu.web.js
@@ -7,9 +7,12 @@ import * as DropdownMenu from '@radix-ui/react-dropdown-menu';
 
 const Root = _ref => {
   let {
-    children
+    children,
+    onOpenChange
   } = _ref;
-  return /*#__PURE__*/React.createElement(DropdownMenu.Root, null, children);
+  return /*#__PURE__*/React.createElement(DropdownMenu.Root, {
+    onOpenChange: (isOpen) => { onOpenChange && onOpenChange(isOpen) },
+  }, children);
 };
 
 Root.displayName = MenuDisplayName.Root;
diff --git a/node_modules/zeego/lib/typescript/menu/types.d.ts b/node_modules/zeego/lib/typescript/menu/types.d.ts
index 55b973b..c7f60d7 100644
--- a/node_modules/zeego/lib/typescript/menu/types.d.ts
+++ b/node_modules/zeego/lib/typescript/menu/types.d.ts
@@ -6,6 +6,7 @@ declare type TextStyle = React.ComponentProps<typeof Text>['style'];
 export declare type MenuRootProps = {
     children: React.ReactNode;
     style?: ViewStyle;
+    onOpenChange?: (open: boolean) => void;
 };
 export declare type MenuTriggerProps = {
     children: React.ReactElement;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by nandorojo** [comment]
Looks like this would be possible for iOS too. The only place it wouldn't work is Android, due to https://github.com/react-native-menu/menu/issues/305.

I'm probably fine with adding the prop if 2/3 platforms support it. And we can mention it in the docs.

**Comment by robertherber** [comment]
> Interesting! I'll look into this.

Awesome! Thanks for this great library that just keeps getting better 👍
