### ISSUE TITLE
[Enhancement] Support Expo Go

### ISSUE THREAD

**Issue by YZahringer** [nandorojo/zeego#15]
Thank you for this awesome lib 👍

Is it planned to support Expo Go without a custom development client on iOS?
I know this is related to the usage of `react-native-ios-context-menu`, but is there a solution planned to make it compatible with Expo Go?

**Comment by nandorojo** [comment]
No, that won’t be possible, unless the Expo team decides to add it. But it’s out of my control since they choose what native libraries get added to Expo Go.

**Comment by YZahringer** [comment]
ok I think the feature request in Expo is here: https://expo.canny.io/feature-requests/p/ios-context-menus
