### ISSUE TITLE
Ability for more detailed customization of the SF Symbols icons

### ISSUE THREAD

**Issue by fobos531** [nandorojo/zeego#19]
`react-native-ios-context-menu` has the option to [customize](https://github.com/dominicstop/react-native-ios-context-menu#object-type-imagesystemconfig) the SF Symbol icon very heavily. We could add this to the `MenuItemIconProps` since we already have an option for `iosIconName` which takes in an SF Symbol.

**Comment by nandorojo** [comment]
I’m open to that!
