### ISSUE TITLE
Any support for testIDs or accessibility labels for the initial menu open?

### ISSUE THREAD

**Issue by MrRio** [nandorojo/zeego#26]
It doesn't seem to work with mobile.dev's Maestro, because we can't pass testIDs or accessibilityLabels into the views.

**Comment by nandorojo** [comment]
I’d accept a PR for this

**Comment by nandorojo** [comment]
Btw, for Maestro on native, I'm not exactly sure how this would work with the menu items.

**Comment by robertherber** [comment]
Did you find a way around it @MrRio? Trying to set up Maestro right now - and can't even seem to trigger it by tapOn with coordinates.

@nandorojo What makes this difficult? Would be interesting to know to be able to find a way forward (I'd be happy with coordinate pressing just to get it working), seems like other iOS native views work fairly well.

**Comment by robertherber** [comment]
I figured out how to it with coordinates, so it's not blocking me anymore. testId would be nice though :)
