### ISSUE TITLE
ReferenceError: React is not defined

### ISSUE THREAD

**Issue by xinha-sh** [nandorojo/zeego#31]
With Solito, following error is shown. Even after importing react in the file, this error doesn't go away

<img width="1080" alt="Screenshot 2022-12-20 at 1 51 08 PM" src="https://user-images.githubusercontent.com/107257599/208618065-314250e6-c020-4833-8c3a-649902e8a636.png">

**Comment by nandorojo** [comment]
did you follow the Next.js instructions?

**Comment by nandorojo** [comment]
Fixed in `1.0.2`.
