### ISSUE TITLE
Error "React is not defined" in monorepo

### ISSUE THREAD

**Issue by jean-ben-guigui** [nandorojo/zeego#32]
I have a bare react native app. React Native v0.70.4.
I installed both react-native-ios-context-menu and @react-native-menu/menu.
When I launch the project I get the following error "can't find variable: React in display-names.js" (cf attached image).
I am able to patch this by adding `import React from 'react';` at the top of the display-names.js file.
Is there something I am doing wrong?

![Simulator Screen Shot - iPhone 14 - 2022-12-21 at 16 16 45](https://user-images.githubusercontent.com/15104156/208903465-e033adc8-272e-4a74-860a-900ed027dcb1.png)

**Comment by nandorojo** [comment]
Interesting, I’ll look into this

**Comment by nandorojo** [comment]
This should be fixed in `1.0.2`.
