### ISSUE TITLE
Where to browse available icons for Android (R.Drawable)

### ISSUE THREAD

**Issue by shawarmaz** [nandorojo/zeego#36]
Looking for a way to visually browse perhaps as a gallery the list of available icons for Android (R.drawable exclusively?). 

How are you guys picking your icons in this case?

**Comment by nandorojo** [comment]
for iOS you download their SF symbols app (i can’t display them for licensing reasons)

i’m actually not sure for android

**Comment by nandorojo** [comment]
i think #9 would be useful for both iOS and Android

**Comment by shawarmaz** [comment]
could be because it's vendor-specific?

**Comment by shawarmaz** [comment]
i'd still assume google would supply their own for their homegrown products

**Comment by nandorojo** [comment]
> could be because it's vendor-specific?

what do you mean?

i’m not sure where the android registry for their icons is

**Comment by nandorojo** [comment]
can you try these https://developer.android.com/reference/kotlin/androidx/compose/material/icons/Icons

**Comment by korayerdem89** [comment]
Checkt out https://developer.android.com/reference/android/R.drawable
