### ISSUE TITLE
Open dropdown menu on long press

### ISSUE THREAD

**Issue by arcln** [nandorojo/zeego#40]
Hello, is it possible to only open dropdown menu when long pressing the trigger? So I can have another behaviour when simply tapping.

**Comment by arcln** [comment]
On Android context menu does the job, on iOS context menu will blur the whole screen + show a preview but I have nothing to preview. Also, context menu on iOS have a delay (#33) which is annoying.

I'd like to use dropdown menu as it have the exact behaviour I want on iOS.

**Comment by nandorojo** [comment]
Just released [`1.5.0`](https://github.com/nandorojo/zeego/releases/tag/v.1.50) which adds this feature. Can you try it and let me know if it works? I didn't have time to test it but I think it should.

```tsx
<DropdownMenu.Trigger action="longPress">
  <Text>Open</Text>
</DropdownMenu.Trigger>
```

**Comment by arcln** [comment]
Just tried it and it works perfectly. Thank you for the blazing fast support!

**Comment by uyasarkocal** [comment]
This feature does not work in the reversed scenario, which is my case:

```
<ContextMenu.Trigger action="press">
    <Text>Open</Text>
</ContextMenu.Trigger>
```

Used libraries:
```
"zeego": "^1.6.2"
"expo-dev-client": "~2.4.6"
"expo": "^49.0.0"
```

**Comment by nandorojo** [comment]
Thanks for flagging that, I would accept a PR with a fix.
