### ISSUE TITLE
iOS icon choose left/right position

### ISSUE THREAD

**Issue by Estevete** [nandorojo/zeego#42]
Is it possible to positionate any icon on iOS? By default it's position is right.

**Comment by nandorojo** [comment]
not sure, does ios apps that?

**Comment by Estevete** [comment]
I don't really know it... if I long press any app, all the iOS dropdowns have the icons right aligned. 

With the package, it's a bit strange having the `DropDown.Sub` with an arrow icon on the left and then if I add any icon to an item, it's right aligned.

![image](https://user-images.githubusercontent.com/19273351/234324924-a875391f-6851-40a7-8878-7059bb13d553.png)
