### ISSUE TITLE
Context and Dropdown menus are not working in sheets

### ISSUE THREAD

**Issue by thecoorum** [nandorojo/zeego#46]
Hey @nandorojo! I recently noticed an issue when both context and dropdown menus stopped working in sheet screens. They are implemented with stack navigator and @gorhom bottom sheet modal which uses portal under the hood (I thought this can be an issue, but was not before). Both of the menus are working on initial stack screen.

I'll append the video demo to highlight the issue. In the demo the component that you can see initially uses exactly the same component that "more actions" button uses in the sheet screen. Also, the "Create transaction" button uses the dropdown menu as you can see by the zoom effect, but it just doesn't open

Any help would be appreciated. Thanks in advance!

## Media
https://github.com/nandorojo/zeego/assets/32096016/1d2302be-7b9b-4e0a-b26d-7b7336153704

**Comment by nandorojo** [comment]
interesting...is this only on iOS? I'm not exactly sure what's unique about sheets

**Comment by thecoorum** [comment]
Okay, so the issue was in the patch-package of the `@gorhom/bottom-sheet` where `BottomSheetModal` was wrapped into
`FullWindowOverlay` implementation with `react-native-screens`. This was done to be able to render BottomSheets over another which are mounted in the screen with `transparentModal` presentation. By implementing screens with a regular bottom sheet (without the patch for window overlay) the context and dropdown menus are rendered again. I think it was some conflict issue, so closing this one

**Comment by alexanderblackh** [comment]
Can definitely confirm I'm seeing this with BottomSheetModal on iOS still, doesn't happen with BottomSheet.
