### ISSUE TITLE
How to use Trigger component as Preview

### ISSUE THREAD

**Issue by e-younan** [nandorojo/zeego#47]
I just tried this library out and like the API quite a bit. I have been using react-native-ios-context-menu before using this library, and it allows for using the "Trigger" in this library as the "Preview" component - is this possible with this library? It seems like the Preview component is always completely separate from the Trigger component.

Edit: I'm referring to the ContextMenu component specifically.

**Comment by nandorojo** [comment]
if you don’t use the optional preview component, then the trigger will be the preview

**Comment by e-younan** [comment]
It seems like I'm running into some kind of bug then - when I was long pressing the context item when it was at the bottom side of the screen, it would open a "fullscreen" context menu, where the preview was completely gone (this was without using the Preview component explicitly). It seems like the preview is working now though.

I'm sure I ran into something, so I'm able to reproduce it, I'll open a ticket.

**Comment by nandorojo** [comment]
maybe the trigger was too large or something, only thing i can think of
