### ISSUE TITLE
Open menu programatically

### ISSUE THREAD

**Issue by hariettem** [nandorojo/zeego#49]
Is there a way to get a ref and just do `.open()`? Or better yet, a `open={true}` flag?

**Comment by nandorojo** [comment]
I'm actually not sure. They differ quite a bit across platforms. It's possible for Web, will have to look into iOS.

**Comment by nandorojo** [comment]
I don't think Apple allows this. Is it really necessary? Can't it just be triggered by tapping/long pressing?

**Comment by radko93** [comment]
Android allows that. Would be quite useful.
