### ISSUE TITLE
using a very tall view as preview causes preview to get cropped

### ISSUE THREAD

**Issue by tconroy** [nandorojo/zeego#52]
_amazing_ work on zeego. I was able to drop this into my app pretty effortlessly. So cool and thanks for building it!

One issue I am running into: if I use a very tall view as my preview component, it appears to get "cut off" on the sides. 

My usecase: I am building an app where users can write posts. If you long-press a post, you get a context menu. This works well for short posts, but for long posts, they get cut off. See attached video. 

https://github.com/nandorojo/zeego/assets/1609336/82a0fe54-0f30-4ca9-a00e-e59c99373187

Any idea how I can fix this? I would expect the entire view to be scaled appropriately to fit into the viewport.

**Comment by nandorojo** [comment]
Hm I’m not sure, it has an issue open for the upstream iOS lib. Could you set a max height of like 100% of the screen width in your preview element perhaps?

**Comment by tconroy** [comment]
Thanks for the tip @nandorojo, unfortunately doesn't appear to help for my use case. Will move this over to the issue in the upstream library. Thanks!
