### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by michaelkremenetsky** [nandorojo/zeego#53]
Is there any way to enable dark mode in Zeego? Didn't see anything about it in the docs.

**Comment by timothyerwin** [comment]
I'm using it and dark mode is working fine for me. I don't think I used any setting.

**Comment by timothyerwin** [comment]
if you are using a native app make sure your app also works in dark mode as well

**Comment by nandorojo** [comment]
@timothyerwin can you show a screenshot of it working? i didn’t think the upstream ios library supported dark mode

**Comment by timothyerwin** [comment]
![IMG_4899](https://github.com/nandorojo/zeego/assets/2653209/75d7b0a4-c4ad-4066-b052-6ee19b732093)

**Comment by timothyerwin** [comment]
the upstream ios library is built on an actual ios component, so yeah, apple supports that

**Comment by nandorojo** [comment]
ah yeah you’re right, works on beatgig too

**Comment by michaelkremenetsky** [comment]
weird that it doesn't work for me on expo dev client, I guess I'll keep playing with it, although I was also hoping there would be some way to toggle it at the app level since my app has its own theme settings that allow you to override the system ones.

**Comment by michaelkremenetsky** [comment]
I figured it out. I fixed it by installing `expo-system-ui`

**Comment by nandorojo** [comment]
good to know, we could add this to the docs

**Comment by Darren120** [comment]
> beatgig

beat gig is made in RN? 0.o

**Comment by Darren120** [comment]
> I figured it out. I fixed it by installing `expo-system-ui`

Hey I have installed expo-system-ui but unable to toggle dark mode for the dropdown. I tried setting the background

      await SystemUI.setBackgroundColorAsync(dark ? "black" : "white");

but the dropdown still light :/
how did u do it?

**Comment by nandorojo** [comment]
i added `userInterfaceStyle: ‘dark’` to my app config since we only do dark mode. but you could try setting it to `automatic`

**Comment by Darren120** [comment]
> i added `userInterfaceStyle: ‘dark’` to my app config since we only do dark mode. but you could try setting it to `automatic`

Thanks, but I thought @michaelkremenetsky was able to toggle it in app via expo system ui

**Comment by michaelkremenetsky** [comment]
> 

Unfortunately, the only way I was able to get it toggle was by changing the system theme in settings. `expo-system-ui` just made it so it would follow the system theme.

**Comment by michaelkremenetsky** [comment]
If anyone finds a way to toggle it in-app I would love to know, I wanted to add in-app theme settings but couldn't find a way to the toggle the zeego components.

**Comment by miafoo** [comment]
I've got an app that supports multiple themes. If a user has selected a darker theme but their iOS appearance is `light` it will also render the context menus as light variants rather than dark versions which is not very nice.

Is there any way to explicitly set the appearance to either `light` or `dark` which overrides the OS level appearance?

**Comment by michaelkremenetsky** [comment]
> 

Thank you the workaround is exactly what I was looking for, I don't think theirs anything built into the library itself

**Comment by nandorojo** [comment]
Hey guys, I'm going to close this out. I'd love to add this to the docs though, can anyone send a PR for dark mode that mentions the override color scheme library? Thank you!

CC @miafoo @michaelkremenetsky

**Comment by michaelkremenetsky** [comment]
Submitted a PR #62

**Comment by Estevete** [comment]
@nandorojo I am facing the issue on Android. Also with the Alert component. I am tracking the issue here https://github.com/expo/expo/issues/27584
