### ISSUE TITLE
collapse

### ISSUE THREAD

**Issue by TomWq** [nandorojo/zeego#54]
I consulted you to provide the example code, and when it crashed on ios, I used expo 49
Exception thrown while executing UI block: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]

**Comment by nandorojo** [comment]
i have no idea how to help with this issue. please provide more context or i will have to close

**Comment by Karthik-B-06** [comment]
Hey @nandorojo, This error is thrown when using the `Context.Menu` and while pressing outside the Preview. Shared a screen recording of the same. 

https://github.com/nandorojo/zeego/assets/35562287/9dc75d5a-71c2-4711-92d0-0c9ba73128f9

**Comment by nandorojo** [comment]
Are you using FlashList from Shopify?

**Comment by Karthik-B-06** [comment]
> Are you using FlashList from Shopify?

Yes. I am.

**Comment by nandorojo** [comment]
In my experience this can result in some bugs with zeego and the preview/aux views. You might need to use the upstream iOS library on iOS with flashlist. They’re doing a lot of magic with the list and it might result in an issue.

**Comment by Karthik-B-06** [comment]
Right makes sense. In iOS, is there a way I can make the Preview Background transparent and not a blurred one through the library? Am I missing something here? 

![image](https://github.com/nandorojo/zeego/assets/35562287/b2145180-f85c-4a5f-8dda-2a6306a3c171)
