### ISSUE TITLE
Add custom image support

### ISSUE THREAD

**Issue by zienna** [nandorojo/zeego#7]
Hey there,

Thank you for the great library! I've been trying to implement a dropdown on both Android and iOS but it seems that the DropdownMenu.ItemIcon is just being ignored.
I can only get it to work if I specify iosIconName or androidIconName but I can't use my custom svg or image.

**Comment by nandorojo** [comment]
hey, yeah that’s a constraint of the platforms. they only let you use system icons. there may be a way to add an item image in the future for iOS (unsure about android). the custom icon will render on web only for now.

**Comment by zienna** [comment]
Is there no other way to add a custom svg to it? I've seen other native apps having a non-system image next to the menu

**Comment by nandorojo** [comment]
i don’t know about SVG in particular, but images should be possible. when I have more time I’ll look into it. when I first tried it wasn’t supported by our ios library and I haven’t revisited since, but it may have gotten fixed.

**Comment by nandorojo** [comment]
I got this working, will be live in the next version: 

<img width="472" alt="image" src="https://user-images.githubusercontent.com/13172299/180917010-c3390206-a7f7-403d-9cd4-1e9a3989ded8.png">

It will come with the context menu at #10
