### ISSUE TITLE
V2 RFC

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/zeego#76]
There is one fundamental **breaking change** I'm considering for V2.

I'd like to no longer rely on or even use React Native Web. Instead, we can directly render the components from Radix UI. This means you will have full access to web-only props like `className`.

Since each platform behaves entirely differently, and the `style` prop is only used on web, it feels natural to expose access to all of the web's props.

This will likely not affect too much of your code, though you might need to add a style reset to the `style` prop. And things like transform would have to change to strings. But this is already the case for RNW anyway.

We would still wrap a few Zeego-specific props like `onValueChange` and `onSelect`. But the key here is to let you use `className` and other DOM-related props. This way you can straight up copy and paste from libraries like shadcn on web.

**Comment by itsyoboieltr** [comment]
@nandorojo looking forward to this, this would make using zeego on web much easier

**Comment by nandorojo** [comment]
Released
