### ISSUE TITLE
Custom styling does not work for DropdownMenu - Item, Content, Title

### ISSUE THREAD

**Issue by zienna** [nandorojo/zeego#8]
I've been trying to use custom styles to change the background color or text color of each item on the menu, but the style prop seems to be ignored by each component

**Comment by nandorojo** [comment]
native menus don’t allow styles like that.

see this for what is possible on iOS: https://github.com/dominicstop/react-native-ios-context-menu

**Comment by nandorojo** [comment]
`style` is only used on Web.

**Comment by zienna** [comment]
The screenshot on the home page shows a menu for ios with gray, black, and red text. How can we implement that without style? Or is that feature not supported

**Comment by nandorojo** [comment]
Can you try `destructive` and `disabled`
