### ISSUE TITLE
[iOS] Dropdown menu items ordered incorrectly.

### ISSUE THREAD

**Issue by bojandurmic** [nandorojo/zeego#88]
Hi there, not sure if I am doing something wrong. Here's my code:
```
<DropdownMenu.Root>
  <DropdownMenu.Trigger>
    <TouchableOpacity>
      <Ionicons
        name="add-outline"
        color={colors.foreground.primary}
        size={24}
      />
    </TouchableOpacity>
  </DropdownMenu.Trigger>
  <DropdownMenu.Content>
    <DropdownMenu.Item key="files" onSelect={addFiles}>
      <DropdownMenu.ItemTitle>Add files</DropdownMenu.ItemTitle>
    </DropdownMenu.Item>
    <DropdownMenu.Item key="photos" onSelect={addPhotos}>
      <DropdownMenu.ItemTitle>
        Add photos and videos
      </DropdownMenu.ItemTitle>
    </DropdownMenu.Item>
  </DropdownMenu.Content>
</DropdownMenu.Root>
```

However, this is the result:

![image](https://github.com/nandorojo/zeego/assets/23002116/cb3d38ec-9456-499e-bc17-a5e58678e68c)

Any idea why this is happening and how can I prevent it?

Versions:

```
"zeego": "^1.10.0".
"react-native-ios-context-menu": "^2.5.1",
"react-native-ios-utilities": "^4.4.4",
```

**Comment by jstheoriginal** [comment]
The way context menus works (at least on iOS) is they always render from first to last away from the button that triggers them. so if the menu goes above, the first item is the closes to the + button. If the context menu were rendered under, it would be as you expect. Long press on home screen icons in different spots to see what I mean.

So if you always have the + button down there, just reverse the order and you should get it as you expect.

**Comment by bojandurmic** [comment]
Oooooh. That makes sense. Thanks @jstheoriginal for the explanation. Definitely not something I expected coming from web React background. Closing the issue. :)

**Comment by nandorojo** [comment]
Looks like this could be set with `.ElementOrder.priority` in Swift: https://developer.apple.com/documentation/uikit/uicontextmenuconfiguration/elementorder/priority

It would have to be implemented here in the native library: https://github.com/dominicstop/react-native-ios-context-menu/blob/ac8f878d90717d6d12e875edc7ea6e5e9a852fa3/ios/RNIContextMenuView/RNIContextMenuViewContent%2BUIContextMenuInteractionDelegate.swift#L19
