### ISSUE TITLE
Should we add autocomplete for `iosIconName`?

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/zeego#9]
The list of iOS icons is here: https://github.com/noahsark769/sfsymbols.com/blob/master/src/data/symbols.json

It would be easy to add TS autocomplete by turning that file into a union type. However, I worry that it might make the types slow.

Maybe we could do something like:

```tsx
import * as DropdownMenu from 'zeego/dropdown-menu'
import { iosIconName } from 'zeego/ios-icons'

<DropdownMenu.ItemIcon iosIconName={iosIconName("xmark.circle.fill")} />
```

That way, you get autocomplete from `iosIconName` as a pure convenience feature, but it doesn't slow down TS if you don't use it. I don't know for fact this would slow it down, but with 2k + items I can only assume.

**Comment by jesuscovam** [comment]
could it be simpler as an enum?

**Comment by nandorojo** [comment]
at runtime an enum would be a giant object, so probably better to keep it as strings and offload any work to the type checker only

**Comment by nandorojo** [comment]
Done in 1.4
