### ISSUE TITLE
Prevent ContextMenu Preview from dismissing ContextMenu when pressed

### ISSUE THREAD

**Issue by ChristopherGabba** [nandorojo/zeego#97]
I am trying to figure out a way to add a button inside a context menu preview. No matter what happens when I press that button, it dismisses the context menu. Unlike the Context Menu items that have a `shouldDismissWhenPressed` prop that works well, the preview does not have this. 

Is there a way to do this?

**Comment by nandorojo** [comment]
I believe the preview does not support nested pressables. However, you can do `onPress` directly on the `Preview` component:

```tsx
<Preview onPress={() => ...} />
```
