### ISSUE TITLE
[bug]: android and iOS requires text content requires to be inside `<Text>` tag

### ISSUE THREAD

**Issue by arpitv96171** [nandorojo/zeego#99]
When using just the string, the following error is thrown:
Code being used:
`<ContextMenu.ItemTitle>
      Redo
  </ContextMenu.ItemTitle>`

Error received:
<img width="373" alt="Screenshot 2024-08-27 at 22 04 23" src="https://github.com/user-attachments/assets/1212aaec-73c0-464e-ae1d-3caca5e145af">

When using text with the `Text` tag, the following error is thrown:
Code being used:
`<ContextMenu.Item key="redo" textValue="Redo">
    <ContextMenu.ItemTitle>
          <Text>Redo</Text>
     </ContextMenu.ItemTitle>
</ContextMenu.Item>`

Error received:
<img width="363" alt="Screenshot 2024-08-27 at 21 59 06" src="https://github.com/user-attachments/assets/82d35631-0bc1-46f9-b5e4-56cd27cdbcd6">

Package Versions:
React Native: 0.74.5
Expo: 51.0.31
Zeego: 1.10.0

**Comment by nandorojo** [comment]
You need to share way more code. The original error doesn’t seem to be related to zeego

**Comment by arpitv96171** [comment]
To be specific, the problem appears to be in the `packages/zeego/src/menu/create-ios-menu/index.ios.tsx` and `packages/zeego/src/menu/create-android-menu/index.android.tsx`

`const ItemTitle = create(({ children }: MenuItemTitleProps) => {
    if (typeof children != 'string') {
      throw new Error('[zeego] <ItemTitle /> child must be a string')
    }
    return <>{children}</>
  }, 'ItemTitle')`

When a string child is passed, it results in an error due to children not being wrapped in `<Text>` component for android and iOS.
When non-string child is passed, zeego errors with error as mentioned in the code.

**Comment by nandorojo** [comment]
Please share your full code you used for me to help. You should be passing a string directly to ItemTitle. If you want to pass a text node, then you need to create a custom component using the Custom Components guide in the docs

**Comment by arpitv96171** [comment]
Surprisingly it's working alright now. I'll close this issue.
I will raise one if any issue comes up in the future
